In [1]:
import torch

from flash_ansr import FlashANSRDataset, get_path, FlashANSRTransformer

In [2]:
dataset = FlashANSRDataset.from_config(get_path('configs', 'v9.0', 'dataset_val.yaml'))

Compiling Skeletons: 100%|██████████| 4999/4999 [00:00<00:00, 29023.13it/s]


In [3]:
ansr = FlashANSRTransformer.from_config(get_path('configs', 'v9.0', 'nsr.yaml'))

In [18]:
for batch in dataset.iterate(steps=2, batch_size=2, preprocess=True):
    batch = dataset.collate(batch, device='cpu')

    data_tensor = torch.cat([batch['x_tensors'], batch['y_tensors']], dim=-1)

    print(batch['input_ids'][:, :10])
    print(batch['input_num'][:, :10])

    logits, num_out = ansr.forward(batch['input_ids'], data_tensor, input_num=batch['input_num'].unsqueeze(-1))

tensor([[ 7,  6,  1, 11,  6, 11,  8,  6, 24, 32],
        [ 1, 15,  8,  6, 24, 32,  2,  0,  0,  0]])
tensor([[nan, 13., nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])
tensor([[ 7,  6,  1, 29, 28, 14, 31,  2,  0,  0],
        [ 7,  6,  1,  8, 32, 11, 31, 11, 32,  8]])
tensor([[nan,  6., nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, 17., nan, nan, nan, nan, nan, nan, nan, nan]])
