In [1]:
import torch

from flash_ansr import FlashANSRDataset, get_path, FlashANSRTransformer

In [2]:
dataset = FlashANSRDataset.from_config(get_path('configs', 'v9.0', 'dataset_val.yaml'))

Compiling Skeletons: 100%|██████████| 200/200 [00:00<00:00, 46707.17it/s]


Compiling Skeletons: 100%|██████████| 4999/4999 [00:00<00:00, 31634.61it/s]


In [3]:
ansr = FlashANSRTransformer.from_config(get_path('configs', 'v9.0', 'nsr.yaml'))

In [4]:
for batch in dataset.iterate(steps=2, batch_size=2, preprocess=True):
    batch = dataset.collate(batch, device='cpu')

    data_tensor = torch.cat([batch['x_tensors'], batch['y_tensors']], dim=-1)

    print(batch['input_ids'][:, :10])
    print(batch['input_num'][:, :10])

    logits, num_out = ansr.forward(batch['input_ids'], data_tensor, input_num=batch['input_num'].unsqueeze(-1))

tensor([[ 1,  8,  6,  9, 31, 11, 32, 33,  2],
        [ 1,  8, 33, 24, 25, 33,  2,  0,  0]])
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan]])
torch.Size([2, 9, 1])
torch.Size([2, 512, 4])
tensor([[ 7,  6,  1, 29, 14,  9, 24, 24, 31, 25],
        [ 1,  8, 33,  8, 33, 14, 11,  8,  6, 31]])
tensor([[nan, 13., nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])
torch.Size([2, 15, 1])
torch.Size([2, 440, 4])
