In [10]:
from flash_ansr import FlashANSRDataset, get_path
import torch

In [11]:
dataset = FlashANSRDataset.from_config(get_path('data', 'ansr-data', 'test_set', 'feynman', 'dataset.yaml'))

Compiling Skeletons: 100%|██████████| 42/42 [00:00<00:00, 44767.67it/s]


In [12]:
noise_level = 1e-3

In [18]:
for batch in dataset.iterate(size=1):
    input_ids, x_tensor, y_tensor, labels, constants = FlashANSRDataset.collate_batch(batch, device='cpu')
    print(input_ids)
    print(labels)
    print(constants)
    print(x_tensor[:3])
    print(y_tensor[:3])
    print(y_tensor.dtype)
    
    y_tensor_noisy = y_tensor + (noise_level * y_tensor.std() * torch.randn_like(y_tensor))
    print(y_tensor_noisy[:3])
    print(y_tensor_noisy.dtype)

    X = x_tensor.cpu().numpy()[0]
    print(X.dtype)
    y = y_tensor_noisy.cpu().numpy()[0]
    print(y.dtype)

tensor([ 1, 10, 30, 10, 31, 32,  2])
tensor([10, 30, 10, 31, 32,  2])
[]
tensor([[-1.8017, -1.4677, -4.3273],
        [-0.5928, -1.6034, -2.4563],
        [-1.6222, -2.5525,  2.6207]])
tensor([[-11.4430],
        [ -2.3349],
        [ 10.8508]])
torch.float32
tensor([[-11.4292],
        [ -2.3487],
        [ 10.8597]])
torch.float32
float32
float32
